language: ruby
dist: trusty
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install -y tshark colordiff
  # docs say that to run as non-root one needs to change settings and log out/back in -
  # can't be done on travis so this is a workaround
  # DANGER - don't do any of the following lines apart from on travisci - it is to enable root to run scripts anywhere
  - sudo sed -i 's/disable_lua = true/disable_lua = false/g' /usr/share/wireshark/init.lua
  - sudo sed -i 's/run_user_scripts_when_superuser = false/run_user_scripts_when_superuser = true/g' /usr/share/wireshark/init.lua
script:
  - ./.travis/test.sh
